### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by ffaf1** [julkaswieta/lost#1] opened 2023-05-11 14:02 UTC
```
f@mkiii:/tmp/lost-build$ make
[  0%] Built target copy_resources
[  6%] Built target sfml-system
[ 24%] Built target sfml-window
[ 40%] Built target sfml-graphics
[ 41%] Built target lib_tile_level_loader
[ 68%] Built target Box2D
[ 69%] Built target lib_ecm
[ 81%] Built target sfml-audio
[ 82%] Building CXX object CMakeFiles/lib_engine.dir/lib/engine/engine.cpp.o
/tmp/lost/lib/engine/engine.cpp:7:10: fatal error: ../src/save_system.h: No such file or directory
    7 | #include "../src/save_system.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/lib_engine.dir/build.make:82: CMakeFiles/lib_engine.dir/lib/engine/engine.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:385: CMakeFiles/lib_engine.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
f@mkiii:/tmp/lost-build$
```

**Comment by ffaf1** [comment] 2023-10-08 21:07
Is there a solution to this? Am I invoking `cmake` wrong?

edit: `../src/save_system.h` is still missing, maybe you forgot to add it to your git repo? @ryanleslie1997

**Comment by ryanleslie1997** [comment] 2023-10-08 21:40
@Dilloid any ideas what to do about this? I thought it wasn't supported on Linux.

**Comment by ryanleslie1997** [comment] 2023-10-09 00:59
Hi @ffaf1 , as far as I know it doesn't support Linux. I've asked someone else who worked on the project too.

**Comment by Dilloid** [comment] 2023-10-09 01:48
Hey @ffaf1. Unfortunately, (as far as I'm aware because I did not write this part of the program), the saving and loading system uses Windows-specific bindings, and that is the cause of your problem. The team member who did write the system did actually attempt to fix it but had to let it go as we were under time pressure. As much as I would love to give it a go myself, this was a student group project, and we no longer have time to work on it as we are in our final year with an unbelievable amount of work to do. I promise that you are not missing much!

**Comment by julkaswieta** [comment] 2023-10-11 19:23
Closing the issue since there are no plans of adding support for Linux or other OS.

**Closed as not planned** 2023-10-11 19:23 UTC
